### ISSUE TITLE
Error: FFmpeg/avconv not found!

### ISSUE THREAD

**Issue by ShishirAhm3d** [moonstar-x/discord-tts-bot#20]
2020-07-10T18:25:39.375924+00:00 app[web.1]: [36m(6:25:39 PM) - [INFO] - Joined General in Bot Test Server.[0m
2020-07-10T18:25:39.481341+00:00 app[web.1]: [36m(6:25:39 PM) - [INFO] - (TTS): Received googleTTS for hi with language 'en' and speed 1 in guild Bot Test Server.[0m
2020-07-10T18:25:39.505467+00:00 app[web.1]: [31m(6:25:39 PM) - [ERROR] - Error: FFmpeg/avconv not found!
2020-07-10T18:25:39.505469+00:00 app[web.1]:     at Function.getInfo (/app/node_modules/prism-media/src/core/FFmpeg.js:130:11)
2020-07-10T18:25:39.505469+00:00 app[web.1]:     at Function.create (/app/node_modules/prism-media/src/core/FFmpeg.js:143:38)
2020-07-10T18:25:39.505470+00:00 app[web.1]:     at new FFmpeg (/app/node_modules/prism-media/src/core/FFmpeg.js:44:27)
2020-07-10T18:25:39.505471+00:00 app[web.1]:     at AudioPlayer.playUnknown (/app/node_modules/discord.js/src/client/voice/player/BasePlayer.js:47:20)
2020-07-10T18:25:39.505471+00:00 app[web.1]:     at VoiceConnection.play (/app/node_modules/discord.js/src/client/voice/util/PlayInterface.js:71:28)
2020-07-10T18:25:39.505472+00:00 app[web.1]:     at /app/src/classes/TTSPlayer.js:80:45
2020-07-10T18:25:39.505472+00:00 app[web.1]:     at processTicksAndRejections (internal/process/task_queues.js:93:5)[0m

**Comment by moonstar-x** [comment]
Hey there, the error is telling you that ffmpeg is not installed in your computer which is required to run the bot. 

If you're on unix based system, you can install ffmpeg with your package manager. If you're on windows, you can get it from [here](https://ffmpeg.org/download.html).

**Comment by moonstar-x** [comment]
Ah, looking at your log with a bit more attention, I'm noticing that you may be running this from Heroku, right?

**Comment by ShishirAhm3d** [comment]
> Ah, looking at your log with a bit more attention, I'm noticing that you may be running this from Heroku, right?

yes bro i'm trying to run this bot on Heroku..

**Comment by ShishirAhm3d** [comment]
> Ah, looking at your log with a bit more attention, I'm noticing that you may be running this from Heroku, right?

how can i fix that?

**Comment by moonstar-x** [comment]
I think I can help you by adding the ffmpeg static binaries as a node package (which actually makes more sense). I'll see if I can do this later tonight.

**Comment by ShishirAhm3d** [comment]
> I think I can help you by adding the ffmpeg static binaries as a node package (which actually makes more sense). I'll see if I can do this later tonight.

ok bro

**Comment by moonstar-x** [comment]
Sorry for taking so long for this, I've been quite busy. In any case, I've just finished the change on in #21. Since the change is just an specification to the "Deploy to Heroku" button, you will need to either:
* Create a new heroku app by clicking the "Deploy to Heroku" button in the README.
* Or, going into your existing app's dashboard, head over to settings, and under buildpacks, add a new one with the following url: `https://github.com/jonathanong/heroku-buildpack-ffmpeg-latest.git`

Thanks for letting me know about this issue!
