### ISSUE TITLE
i am Facing this error how to fix it??

### ISSUE THREAD

**Issue by Kabin1234** [moonstar-x/discord-tts-bot#49]
(node:3600) UnhandledPromiseRejectionWarning: Error: FFmpeg/avconv not found!
    at Function.getInfo (/home/runner/discord-tts-bot/node_modules/prism-media/src/core/FFmpeg.js:143:11)
    at Function.create (/home/runner/discord-tts-bot/node_modules/prism-media/src/core/FFmpeg.js:156:38)
    at new FFmpeg (/home/runner/discord-tts-bot/node_modules/prism-media/src/core/FFmpeg.js:45:27)
    at AudioPlayer.playUnknown (/home/runner/discord-tts-bot/node_modules/discord.js/src/client/voice/player/BasePlayer.js:47:20)
    at VoiceConnection.play (/home/runner/discord-tts-bot/node_modules/discord.js/src/client/voice/util/PlayInterface.js:71:28)
    at TTSPlayer.play (/home/runner/discord-tts-bot/src/classes/tts/TTSPlayer.js:61:41)
    at TTSPlayer.say (/home/runner/discord-tts-bot/src/classes/tts/TTSPlayer.js:45:12)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
(node:3600) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:3600) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by L0SER8228** [comment]
You need to install ffmpeg
`https://github.com/jonathanong/heroku-buildpack-ffmpeg-latest.git`
try adding this buildpack and redeploy

**Comment by moonstar-x** [comment]
> You need to install ffmpeg
> `https://github.com/jonathanong/heroku-buildpack-ffmpeg-latest.git`
> try adding this buildpack and redeploy

In addition to this response, this works if you're using Heroku.

From that error path I imagine you're using Repl.it.

For Repl.it, I don't think you have access to the OS's package manager which makes it hard to install native dependencies. Try running this command:

 ```
npm install ffmpeg-static
```

BTW, I've seen people getting varied results when running bots on Repl.it that require voice channel connectivity.

**Comment by hades4626488** [comment]
> > You need to install ffmpeg
> > `https://github.com/jonathanong/heroku-buildpack-ffmpeg-latest.git`
> > try adding this buildpack and redeploy
> 
> In addition to this response, this works if you're using Heroku.
> 
> From that error path I imagine you're using Repl.it.
> 
> For Repl.it, I don't think you have access to the OS's package manager which makes it hard to install native dependencies. Try running this command:
> 
> ```
> npm install ffmpeg-static
> ```
> 
> BTW, I've seen people getting varied results when running bots on Repl.it that require voice channel connectivity.

Thank you!
