### ISSUE TITLE
Key not found in database

### ISSUE THREAD

**Issue by Natame** [moonstar-x/discord-tts-bot#65]
🐛 Describe the Bug
Keep getting Key not found in database error randomly after running the bot

✏️ Steps to Reproduce
1. reinstall all modules
2.  reconfigure bot settings on the discord server

😕 Expected Behavior
Expected bot to run without error

📜 Log
```
/www/wwwroot/discordbot/NetaTTS/node_modules/levelup/lib/levelup.js:188
        err = new NotFoundError('Key not found in database [' + key + ']', err)
              ^
Error [NotFoundError]: Key not found in database [829958692857970688:935454436199907358:tts_settings]
    at /www/wwwroot/discordbot/NetaTTS/node_modules/levelup/lib/levelup.js:188:15
    at /www/wwwroot/discordbot/NetaTTS/node_modules/encoding-down/index.js:75:21 {
  [cause]: [Error: NotFound: ]
}
```
📷 Screenshots
![error](https://user-images.githubusercontent.com/20907073/150978963-acfde2b9-932a-439c-afef-72fe209f427c.png)

❓ Other Information
Node Version: v17.4.0
Bot version: 4.0.4

**Comment by moonstar-x** [comment]
Hey there, do you perhaps know if you ran any command that triggered this error or did it happen randomly?

Maybe the bot left a server or did it join a new one?

I'm kinda surprised how unhelpful the stack trace is lol.

**Comment by Natame** [comment]
Hello, the error just randomly got triggered even without running any command since I start the bot

I did kick the bot and invite it again before (to skip global commands to refresh), maybe that's the cause of this error

**Comment by moonstar-x** [comment]
Ah I think I got it,

Did you perhaps delete a channel when the bot crashed?

**Comment by Natame** [comment]
nah I didn't do anything when the bot crashed

I had to make a new one and it runs fine now without error, thanks

**Comment by moonstar-x** [comment]
Are you sure?

I'm gonna try later today but I almost 100% sure that this happens when using the level data provider and deleting a channel.

**Comment by Natame** [comment]
Yes,

The new one has been run for 24h without error, I don't know what makes the old one error

also there's auto channel that will get deleted when there's no one in the voice channel, could be this cause the issue?

**Comment by moonstar-x** [comment]
I still haven't tried it, but something tells me that a channel getting removed (whether it's text or voice, whatever) would make the bot crash.

**Comment by Natame** [comment]
just found that auto channel caused the issue, when a channel got deleted, the bot crashed

is there a way to reset the bot settings/database?

**Comment by moonstar-x** [comment]
As I suspected.

I'm going to try to get that fixed tonight.

You don't need to reset the database.

The problem happens because the bot has also a feature where you can save settings for a specific channel so you can use the TTS functionality without the need to use any command. When a channel gets deleted, the bot removes the data stored for that channel, but since your auto channel never had any data associated to it then the bot crashes because it tried to remove something that doesn't exist.

**Comment by moonstar-x** [comment]
Fixed in #66.
